### ISSUE TITLE
Plugin not working on windows with psy/psysh >= v0.11.3 (file_exists(): Unable to find the wrapper "hoa")

### ISSUE THREAD

**Issue by abrampl** [Roboroads/laravel-tinker#164] opened 2022-06-01 08:27 UTC
**Bug description**

```php
Uncaught Psy\Readline\Hoa\ConsoleTput::parse(): (0) Terminfo file  does not exist.
```

**Environment (please complete the following information):**
 - IDE & Version: PHPStorm 2020.2.4
 - PHP Version: 8.1
 - OS: Windows 10
 - Laravel Tinker plugin version : 2.3.3
 - Interpreter Type: Local
 - Laravel Version: v9.15.0
 - Tinker version: v2.7.2

**Comment by Roboroads** [comment] 2022-06-01 13:12
# Temporary workaround until i get around to fixing this

> rollback psy/psysh to version 0.11.2
> 
> `composer require psy/psysh:0.11.2 --dev`
> 
> and will work

**Comment by Roboroads** [comment] 2022-06-08 23:23
This might be a windows specific issue, cannot reproduce on my linux machine with psysh 0.11.3 and 0.11.5

**Comment by daniser** [comment] 2022-06-10 08:24
[Рrobably related](https://github.com/bobthecow/psysh/issues/722).

**Comment by Roboroads** [comment] 2022-06-10 09:36
It is indeed. Psysh bug.

**Comment by leandrodiogenes** [comment] 2022-07-28 20:49
Fixed after psy/psysh v0.11.8 release, please update.

**Comment by Roboroads** [comment] 2022-07-28 23:30
You should update psysh in your project, nothing I can do here 😜

**Comment by Roboroads** [comment] 2022-07-28 23:32
@abrampl could you confirm this?

**Comment by Roboroads** [comment] 2022-08-01 21:36
Can anyone tell me it's fixed with the new psysh?

**Comment by daniser** [comment] 2022-08-02 08:44
> Can anyone tell me it's fixed with the new psysh? I can't reproduce this on the broken versions :P

I can confirm it's fixed.

**Comment by Roboroads** [comment] 2022-08-04 09:10
Awesome, closing then <3

**Closed by Roboroads** 2022-08-04 09:10 UTC
Labels: temporary workaround available, external bug
