### ISSUE TITLE
[Bug]: Errors not being parsed

### ISSUE THREAD

**Issue by rubikovakocka** [Roboroads/laravel-tinker#342] opened 2024-05-29 09:35 UTC
### Short bug description

When I run code with errors, it doesn't show them

### Extended bug description

Tried changing the PHP interpreter, didn't help. I use shortcut ALT + T (Smart action)
However, when I run with Play button (Run on 3v4l.org), it shows the errrors.

### Your project is not the problem

- [X] I tried using a fresh laravel install - I'm fairly certain it has nothing to do with my project.

### How to reproduce?

1. Type some code with errors.
2. Run the Tinker.
3. No output.

### Expected behavior

Should print error.

### Screenshots

![image](https://github.com/Roboroads/laravel-tinker/assets/55852889/40a9fecf-c13a-4e15-9a4b-4fab058b0e5f)

### IDE & Version

PhpStorm 2024.1.1

### PHP Version

7.4.33

### OS and version

Linux Ubuntu 22.04.4 LTS (Jammy Jellyfish)

### Laravel Tinker plugin version

2.7.0

### Interpreter type

Local

### Laravel Version

v8.63.0

### Tinker version

v2.6.1

### Psysh version

v0.10.8

### Additional Context

It used to work before, I had this issue for over a month.

Any help here would be appreciated, thank you!

**Comment by Roboroads** [comment] 2024-06-03 12:08
Hi! I'm aware of the issue - I'm trying to contact JetBrains to help me figure this out - without much response yet.

Since this is a duplicate of https://github.com/Roboroads/laravel-tinker/issues/320 I will close this one.

**Closed by Roboroads** 2024-06-03 12:08 UTC
Labels: bug

**Comment by rubikovakocka** [comment] 2024-06-04 11:27
Fingers crossed my friend :crossed_fingers:
