### ISSUE TITLE
Laravel Tinker cause issues in PHP Storm

### ISSUE THREAD

**Issue by imami** [Roboroads/laravel-tinker#102] opened 2021-09-16 08:54 UTC
Laravel Tinker cause issues in PHP Storm:
1. Slows down the PHP Storm.
2. Prevents auto code completion and suggestions.
3. Sometimes cause issues with context-menu in project panel.

Laravel Tinker : v2.2.1
PhpStorm v2021.2.1

none of these issues exist before updating (also clean installing) PhpStorm v2021.2.1
and everything become ok when disabling the plugin.

**Comment by Roboroads** [comment] 2021-09-16 20:41
Duplicate of #61 - I need a way to reproduce the issue since I con't reproduce it whatever I try to do.

**Closed by Roboroads** 2021-09-16 20:41 UTC
Labels: bug, duplicate
