### ISSUE TITLE
Null file after execution

### ISSUE THREAD

**Issue by Davidnadejdin** [Roboroads/laravel-tinker#11] opened 2020-09-04 14:27 UTC
after executing the code, a null file is created
![image](https://user-images.githubusercontent.com/40993387/92250292-b54e8e80-eee4-11ea-939a-6a31c7cd85e5.png)

**Comment by Roboroads** [comment] 2020-09-04 15:58
Looks like a windows problem - I have not encountered this on my unix machines.

**Comment by msouto346** [comment] 2020-09-05 11:38
The same thing happens to me on windows10

**Comment by Roboroads** [comment] 2020-09-06 01:34
Does the null file have any content? I want to fix this but i have to install some windows somewhere.

**Comment by msouto346** [comment] 2020-09-06 07:30
Nope, and the only way to clean it from untracked files in git is by doing git clean -fd

**Comment by Davidnadejdin** [comment] 2020-09-06 11:26
> Does the null file have any content? I want to fix this but i have to install some windows somewhere.

install in virtual machine

**Comment by adelf** [comment] 2020-09-09 15:28
@Roboroads you can try to create a file editor with empty document, without any virtual files. Right in the tool window for example. Or use scratch files.

**Comment by Roboroads** [comment] 2020-09-09 21:45
@adelf Is the null file caused by a LightVirtualFile? The whole ponint of using an editor tab is so that you can use all the PHP editor functions.
Why scratch files? The point was the console not being accessible except from the shortcut.

Note: I'm new to Kotlin and JB PlugDev.

**Comment by adelf** [comment] 2020-09-10 21:22
>Is the null file caused by a LightVirtualFile?
Might be.

The editor can be used in the toolbox window and all PHP editor functions will be available. Little screenshot from "tinker" branch of Laravel Idea(seems it will never be merged :) ):
![image](https://user-images.githubusercontent.com/2818394/92805558-e423a380-f3c1-11ea-98cd-903d1cf79dc3.png)

Inside tool window class:
```kotlin
    private val editor = createEditor()

    private fun createEditor(): Editor {
        val file = PsiFileFactory.getInstance(project).createFileFromText("tinker.php", PhpLanguage.INSTANCE, "<?php\n")

        return EditorFactory.getInstance().createEditor(file.viewProvider.document!!, project, PhpFileType.INSTANCE, false)
    }
```
`editor.component` then can be used to put to the toolwindow... this is not easy, since you use forms from "form editor"... but if you're ok with this design I can try to make a PR. It could solve some issues like #16

**Comment by Roboroads** [comment] 2020-09-10 22:10
My whole plan for the plugin was for it to be a tab, like how you can run database queries from a sql console/file. The screen out of the idea plugin is not feeling right in mind for some reason, in respect to how jetbrains have made their tools.I just hadn't had the time yet to investigate, but will definitely check if the lvf is the problem.Also, thanks for helping and offering PRs!

**Comment by Roboroads** [comment] 2020-09-15 23:15
Progress on the matter - it's not my plugin that is creating the null file. It's happening somewhere in Psysh. Running the command I run for the plugin without using the plugin creates the null file aswell.

**Comment by Roboroads** [comment] 2020-09-15 23:24
Found it!

**Closed** 2020-09-15 23:27 UTC
Labels: bug
