### ISSUE TITLE
Add app termination

### ISSUE THREAD

**Issue by emargareten** [Roboroads/laravel-tinker#169] opened 2022-06-09 08:02 UTC
**Is your feature request related to a problem? Please describe.**
Some events only dispatch after app terminated / object destruction

**Describe the solution you'd like**
Add a simple `$app->terminate()` (or `$kernal->terminate($input???, $status???)`) in tinker_run.php after execution.

**Comment by Roboroads** [comment] 2022-06-09 08:47
Does _normal_ tinker do this?

**Comment by emargareten** [comment] 2022-06-09 09:13
normal tinker never ends

**Comment by lazer-hybiz** [comment] 2022-06-09 09:19
This is one of the stuff I hate in tinker, sometimes I have to manually call `__destruct` for things to work.

Also see https://github.com/laravel/telescope/issues?q=terminate+tinker

**Comment by Roboroads** [comment] 2022-06-09 09:21
Normal tinker stops when you type "q" or "exit" - if that does what you want it to do, then the latest update (2.3.4) will do exactly that.

If not: I can add an option to the settings to enable termination or not.

**Comment by emargareten** [comment] 2022-06-09 09:26
`q` and `exit` throws the BreakException I don't think it terminates the application.

**Comment by emargareten** [comment] 2022-06-09 12:32
@Roboroads does this zip include the latest changes? I'm still using 2022.1

**Comment by Roboroads** [comment] 2022-06-09 12:33
@emargareten This zip contains #170

**Comment by emargareten** [comment] 2022-06-09 12:34
Can I use it with 2022.1

**Comment by Roboroads** [comment] 2022-06-09 12:34
Yes but docker interpreters won't work

**Comment by Roboroads** [comment] 2022-06-09 13:45
[Laravel Tinker-2.4.0.zip](https://github.com/Roboroads/laravel-tinker/files/8870915/Laravel.Tinker-2.4.0.zip)
With this one too?

**Comment by emargareten** [comment] 2022-06-09 13:57
no, now it's fine.
but.. now I see `dump()` doesn't work

**Comment by emargareten** [comment] 2022-06-15 09:27
@Roboroads It does work, I think you can go ahead with this.

I do have another issue I think it started in version 2.3.4, sometimes the output displays only partially or doesn't display at all. (I might have had this issue on rare occasions before but now it happens like 50% of the time)

**Comment by Roboroads** [comment] 2022-06-15 10:35
Maybe you should create a new issue for that problem and see if other people have the same problem since I don't have it it and need a way to reproduce it to be able to fix it 🥲

**Comment by Roboroads** [comment] 2022-08-01 16:32
Will be in 2.4.0

**Closed by Roboroads** 2022-08-01 16:32 UTC
Labels: feature request

**Comment by Roboroads** [comment] 2022-08-01 17:31
2.4.0 will be available this week after JB accepts it, which includes this issue.
