### ISSUE TITLE
Refreshing index issue

### ISSUE THREAD

**Issue by fawzanm** [Roboroads/laravel-tinker#100] opened 2021-09-15 05:46 UTC
**Bug description**
it's a very strange bug. I've been trying to use this plugin for about 3 months now and I keep on getting a "Indexing in progress" message flickering in PHPStorm. It only happens when Laravel Tinker plugin is enabled. I've tried to re-install and invalidate cache many times but I couldn't get it fixed. Anyone else faced this issue? 

**To Reproduce**
I don't have any particular steps as I am using the latest version of the plugin and PHPStorm. 

**Environment
 - IDE & Version: 2021.2.1
 - PHP Version: 8.0.7
 - OS: MacOS 11.5.2 
 - Laravel Tinker plugin version : 2.2.1
 - Interpreter Type: Local
 - Laravel Version: 8.*
 - Tinker version: v2.6.1

**Comment by Roboroads** [comment] 2021-09-15 11:17
Sounds like a duplicate of #61 - I really need a good way to reproduce this to fix it tho. Some say it's project specific.

**Closed by Roboroads** 2021-09-15 11:17 UTC
Labels: bug
